# Generated by Django 3.1.7 on 2021-05-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210525_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cook_img',
            new_name='user_img',
        ),
    ]
