# Generated by Django 3.2 on 2021-05-11 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('cook_img', models.ImageField(blank=True, default='../static/images/anonym=user.png', null=True, upload_to='')),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('recipe_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('ingredients', models.TextField(max_length=1000, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('preparation_time', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=30, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='category.Category')),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='cookbook.cook')),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='like_recipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to='cookbook.Recipe'),
        ),
        migrations.AddField(
            model_name='cook',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
