# Generated by Django 3.2 on 2021-05-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20210513_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='data_created',
            new_name='creation_date',
        ),
    ]
