# Generated by Django 3.2 on 2021-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
