# Generated by Django 3.2 on 2021-05-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_alter_recipe_preparation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='amount',
            new_name='quantity',
        ),
    ]
